# Generated by Django 6.0.3 on 2026-03-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sesion', models.CharField(max_length=100, unique=True)),
                ('puntuacion', models.IntegerField(default=0)),
                ('movimientos', models.IntegerField(default=0)),
                ('estado_tablero', models.TextField(default='[]')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
