# Generated by Django 6.0.3 on 2026-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_sesionjuego_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionjuego',
            name='intentos_restantes',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='sesionjuego',
            name='nivel',
            field=models.CharField(default='basico', max_length=20),
        ),
    ]
