# Generated by Django 6.0.3 on 2026-03-16 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_sesionjuego_intentos_restantes_sesionjuego_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionjuego',
            name='tiempo_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionjuego',
            name='tiempo_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
