# Generated by Django 6.0.3 on 2026-03-16 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_sesionjuego_tiempo_fin_sesionjuego_tiempo_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionjuego',
            name='resultado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_victorias', models.IntegerField(default=0)),
                ('total_derrotas', models.IntegerField(default=0)),
                ('total_partidas', models.IntegerField(default=0)),
                ('tiempo_total', models.IntegerField(default=0)),
                ('nivel_basico_jugado', models.IntegerField(default=0)),
                ('nivel_medio_jugado', models.IntegerField(default=0)),
                ('nivel_avanzado_jugado', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
